default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4


development:
  <<: *default
  database: sling-server_development

test:
  <<: *default
  database: sling-server_test
