# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d99c4b003b5e1c577a26c6e3899f7bfbcb73a9cadb7fa46de71ab3b4ebd13b5d9ee3da86e5ee25d76a981e65cf1314fe31ece4b0c3c7dbce92a434de32b41708

test:
  secret_key_base: 6e59774d785be41795c4fb43197eb942a7bc8672e5f6e1ade1840c6d2e6c9dc156e46b3d4fa2ecaabbb3e5609f2976abc00d8a09477c3a64496c6d98516b0ee2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
